### ISSUE TITLE
Error “The value 'gre' is not supported for conversion.”

### ISSUE THREAD

**Issue by mani9876** [mogikanin/DotRas#2]
Hello,

on Windows Server 2016 Standard I always get the error “The value 'gre' is not supported for conversion.” if I run RasDevice.GetDevices().

I already tried the newest version from github. This is the whole error:
System.NotSupportedException: The value 'gre' is not supported for conversion.
   bei DotRas.Internal.ThrowHelper.ThrowNotSupportedException(String message, Object[] args)
   bei DotRas.RasDeviceTypeConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   bei DotRas.RasDevice.Create(String name, String deviceType)
   bei DotRas.Internal.RasHelper.GetDevices()
   bei DotRas.Samples.CreateAndDialVpnEntry.MainForm.CreateEntryButton_Click(Object sender, EventArgs e) in C:\Users\Administrator\Desktop\DotRas-master\examples\src\WinForms\CreateAndDialVpnEntry\CS\CreateAndDialVpnEntry\MainForm.cs:Zeile 47.

Have you got any hints for me?

Thanks

**Comment by mogikanin** [comment]
It's fails because of [GRE tunneling](https://docs.microsoft.com/en-us/windows-server/remote/remote-access/ras-gateway/gre-tunneling-windows-server) available since Server 2016. I've added support for this device, should work now.

**Comment by mani9876** [comment]
You are a genius! It is working now, thank you so much!
