### ISSUE TITLE
Set remote IP Address via IPCP

### ISSUE THREAD

**Issue by mani9876** [mogikanin/DotRas#3]
I know it's not really an issue, but maybe it's possible to add this feature, or it is also possible that windows can't provide that feature.

I need to set the remote IP Address of the server I am connecting to, if I use linux pppd it's simple by adding localIP:remoteIP when calling the server.

Is there a possibility to add that feature to DotRas?

Thanks!

**Comment by mogikanin** [comment]
No, I think this is not a possible. Basically, DotRas is just a wrapper around native [RAS](https://docs.microsoft.com/en-us/windows/desktop/rras/remote-access-service-reference) api with some simplification.

**Comment by mani9876** [comment]
Thank you !
